# (Edited Version) Measuring Word Similarity with BERT -- English Language Public Domain Poems

By [The AI for Humanists](https://www.aiforhumanists.com/) Team


How can we measure the similarity of words in a collection of texts? For example, how similar are the words "nature" and "science" in a collection of 16th-20th century English language poems? Do 20th-century poets use the word "science" differently than 16th-century poets? Can we map all the different uses and meanings of the word "nature"?

The short answer is: yes! We can explore all of these questions with BERT, a natural language processing model that has revolutionized the field.

BERT turns words or tokens into vectors — essentially, a list of numbers in a coordinate system (x, y). We can then use the geometric similarity between these resulting vectors as a way to represent varying types of similarity between words.

## In This Notebook
In this Colab notebook, we will specifically analyze a collection of poems scraped from [Public-Domain-Poetry.com](http://public-domain-poetry.com/) with the [DistilBert model](https://huggingface.co/transformers/model_doc/distilbert.html) and the HuggingFace Python library. DistilBert is a smaller — yet still powerful! — version of BERT. By using the rich representations of words that BERT produces, we will then explore the multivalent meanings of particular words in context and over time.

We hope this notebook will help illustrate how BERT works, how well it works, and how you might use BERT to explore the similarity of words in a collection of texts. It is surprising, for example, that BERT works as well as it does, without any fine-tuning, on poems that were published hundreds of years before the text data it was trained on (Wikiepdia pages and self-published novels).

But we also hope that these results will expose some of the limitations and challenges of BERT. We have to disregard poetic line breaks, for example, and we see that BERT has trouble with antiquated words like "thine," which don't show up in its contemporary vocabulary.

The plot above displays a preview of our later results. This is what we're working toward!

You can hover over each point to see the instance of each word in context. If you press `Shift` and click on a point, you will be taken to the original poem on Public-Domain-Poetry.com. Try it out!

## **Import necessary Python libraries and modules**

Ok enough introduction! Let's get started.

To use the HuggingFace [`transformers` Python library](https://huggingface.co/transformers/installation.html), we first need to install it with `pip`.

In [2]:
# !pip install transformers

Then we will import the DistilBertModel and DistilBertTokenizerFast from the Hugging Face `transformers` library. We will also import a handful of other Python libraries and modules.

In [3]:
# For BERT
from transformers import DistilBertTokenizerFast, DistilBertModel

# For data manipulation and analysis
import pandas as pd
pd.options.display.max_colwidth = 200
import numpy as np
from sklearn.decomposition import PCA

# For interactive data visualization
import altair as alt

## **Load text dataset**

Our dataset contains around ~30 thousand poems scraped from  http://public-domain-poetry.com/ (*the link doesn't work now*). This website hosts a curated collection of poems that have fallen out of copyright, which makes them easier for us to share on the web.
You can find the data in our [GitHub repository](https://github.com/melaniewalsh/BERT-4-Humanists/blob/main/data/public-domain-poetry.csv).

We don't have granular date information about when each poem was published, but we do know the birth dates of most of our authors, which we've used to loosely categorize the poems by time period. The poems in our data range from the Middle Ages to the 20th Century, but most come from the 19th Century. The data features both well-known authors — William Wordsworth, Emily Elizabeth Dickinson, Paul Laurence Dunbar, Walt Whitman, Shakespeare — as well as less well-known authors.

Below we will use the Python library `pandas` to read in our CSV file of poems. It is convenient (especially for Colab notebooks) that `pandas` allows you to read in files directly from the web.

To be clear, however, knowledge of `pandas` is not necessary to use BERT. This is simply how we've chosen to load our data. All you really need  is a list of texts (poems, passages, etc.). You can create this list however you are most comfortable.

In [4]:
url = "https://raw.githubusercontent.com/melaniewalsh/BERT-4-Humanists/main/data/public-domain-poetry.csv"

poetry_df = pd.read_csv(url, encoding='utf-8')
# Show 5 random rows
poetry_df.sample(5)

,author,title,text,lifespan,birth_year,death_year,link,period
15557,Madison Julius Cawein,"Beautiful-Bosomed, O Night","I.\n\r\nBeautiful-bosomed, O Night, in thy noon\r\nMove with majesty onward! soaring, as lightly\r\nAs a singer may soar the notes of an exquisite tune,\r\nThe stars and the moon\r\nThrough the cl...",23 March 1865 - 8 December 1914,1865.0,1914.0,http://public-domain-poetry.com/madison-julius-cawein/beautiful-bosomed-o-night-11874,19th Century
24093,Thomas Gent,"1827; Or, The Poet's Last Poem","Ye Bards in all your thousand dens,\r\nGreat souls with fewer pence than pens,\r\nSublime adorers of Apollo,\r\nWith folios full, and purses hollow;\r\nWhose very souls with rapture glisten,\r\nWh...",1780 - ?,1780.0,NaN,http://public-domain-poetry.com/thomas-gent/1827-or-the-poets-last-poem-16242,19th Century
12545,John Greenleaf Whittier,My Dream,"In my dream, methought I trod,\r\nYesternight, a mountain road;\r\nNarrow as Al Sirat's span,\r\nHigh as eagle's flight, it ran.\n\r\nOverhead, a roof of cloud\r\nWith its weight of thunder bowed;...","December 17, 1807-September 7, 1892",1807.0,1892.0,http://public-domain-poetry.com/john-greenleaf-whittier/my-dream-5979,19th Century
13407,John Keats,Answer To A Sonnet By J.H.Reynolds,"Dark eyes are dearer far\r\nThan those that mock the hyacinthine bell.\n\r\nBlue! 'Tis the life of heaven, the domain\r\nOf Cynthia, the wide palace of the sun,\r\nThe tent of Hesperus, and all hi...",31 October 1795-23 February 1821,1795.0,1821.0,http://public-domain-poetry.com/john-keats/answer-to-a-sonnet-by-jhreynolds-6252,19th Century
13123,John Hartley,All Tawk,Some tawk becoss they think they're born\r\nWi' sich a lot o' wit;\r\nSome seem to tawk to let fowk know\r\nThey're born withaat a bit.\r\nSome tawk i' hooaps 'at what they say\r\nMay help ther fe...,1839-1915,1839.0,1915.0,http://public-domain-poetry.com/john-hartley/all-tawk-17954,19th Century

Let's check to see how many poems are in this dataset:

In [5]:
len(poetry_df)

31080

#### **In-class Practice: Exploratory data analysis**
1. Let's check to see which authors show up the most in this dataset (e.g., top 20) to get a sense of its contours:

In [6]:
authors = poetry_df["author"]
author_counts = {}

for author in authors:
    if author in author_counts:
        author_counts[author] += 1
    else:
        author_counts[author] = 1

author_counts = sorted(author_counts.items(), key=lambda item: item[1], reverse=True)
author_counts

[('Robert Herrick', 1464),
 ('Madison Julius Cawein', 1345),
 ('William Wordsworth', 963),
 ('Thomas Moore', 853),
 ('Thomas Hardy', 655),
 ('Rudyard Kipling', 638),
 ('Robert Burns', 499),
 ('John Greenleaf Whittier', 481),
 ('Algernon Charles Swinburne', 461),
 ('Emily Elizabeth Dickinson', 447),
 ('Paul Laurence Dunbar', 417),
 ('John Clare', 382),
 ('William Butler Yeats', 378),
 ('Francesco Petrarca (Petrarch)', 375),
 ('Paul Cameron Brown', 341),
 ('Walt Whitman', 338),
 ('Edgar Lee Masters', 331),
 ('Percy Bysshe Shelley', 330),
 ('Oliver Wendell Holmes', 329),
 ('Walter De La Mare', 329),
 ('Alfred Lord Tennyson', 325),
 ('William Cowper', 308),
 ('Henry Wadsworth Longfellow', 295),
 ('John Hartley', 294),
 ('Banjo Paterson (Andrew Barton)', 283),
 ('Edward Lear', 264),
 ('Friedrich Schiller', 256),
 ('Christina Georgina Rossetti', 241),
 ('Charles Baudelaire', 234),
 ('William Lisle Bowles', 232),
 ('Ralph Waldo Emerson', 226),
 ('Michael Drayton', 225),
 ('Henry Kendall', 214),
 ('Robert William Service', 212),
 ('Alexander Pope', 208),
 ('Robert Browning', 204),
 ('John Frederick Freeman', 202),
 ('D. H. Lawrence (David Herbert Richards)', 189),
 ('Matthew Prior', 187),
 ('Victor-Marie Hugo', 187),
 ('William Ernest Henley', 183),
 ('George Gordon Byron', 181),
 ('Vachel Lindsay', 179),
 ('Thomas Hood', 165),
 ('Robert Lee Frost', 164),
 ('Walter Scott (Sir)', 162),
 ('William Shakespeare', 156),
 ('Matthew Arnold', 150),
 ('Walter Crane', 150),
 ('William Arthur Dunkerley (John Oxenham)', 150),
 ('John Keats', 146),
 ('Arthur Hugh Clough', 145),
 ('Frank Sidgwick', 144),
 ('George Pope Morris', 144),
 ('Philip Sidney (Sir)', 142),
 ('Archibald Lampman', 141),
 ('Jean Ingelow', 141),
 ('William Blake', 141),
 ('Emma Lazarus', 138),
 ('Robert Fuller Murray', 133),
 ('Abram Joseph Ryan', 132),
 ('Laurence Hope (Adela Florence Cory Nicolson)', 132),
 ('William Cullen Bryant', 131),
 ('Walter Savage Landor', 130),
 ('John Milton', 129),
 ('Anna Seward', 126),
 ('Jean Blewett', 126),
 ('John Dryden', 125),
 ('Pamela S. Vining, (J. C. Yule)', 124),
 ('Bliss Carman (William)', 122),
 ('Bret Harte (Francis)', 121),
 ('Edward Powys Mathers (As Translator)', 120),
 ('Henry John Newbolt, Sir', 120),
 ('Herman Melville', 120),
 ('Thomas Gent', 118),
 ("Oscar Fingal O'Flahertie Wills Wilde", 114),
 ('Elizabeth Barrett Browning', 108),
 ('Rosanna Eleanor Leprohon', 108),
 ('Gilbert Keith Chesterton', 105),
 ('Henry Austin Dobson', 103),
 ('Alfred Edward Housman', 102),
 ('Conrad Potter Aiken', 100),
 ('Dante Alighieri', 100),
 ('James Stephens', 99),
 ('Sidney Lanier', 99),
 ('Frances Anne Kemble (Fanny)', 98),
 ('Francis William Lauderdale Adams', 96),
 ('Edna St. Vincent Millay', 94),
 ('George William Russell', 94),
 ('Rupert Brooke', 94),
 ('Edward Dyson', 93),
 ('Victor James Daley', 92),
 ('George Parsons Lathrop', 91),
 ('John Collings Squire, Sir', 90),
 ('William Morris', 90),
 ('Ben Jonson', 88),
 ('Hattie Howard', 87),
 ('Alfred Lichtenstein', 86),
 ('Emily Pauline Johnson', 86),
 ('Joseph Horatio Chant', 86),
 ('Edgar Allan Poe', 85),
 ('Charles Kingsley', 83),
 ('Alan Seeger', 80),
 ('Thomas Frederick Young', 80),
 ('Charles Sangster', 78),
 ('Louisa May Alcott', 78),
 ('Robert Southey', 78),
 ('Eric Mackay', 76),
 ('John Gay', 76),
 ('John Milton Hay', 76),
 ('Siegfried Loraine Sassoon', 75),
 ('Alice Christiana Gertrude Thompson Meynell', 74),
 ('Lewis Carroll', 74),
 ('Ellis Parker Butler', 73),
 ('Hanford Lennox Gordon', 73),
 ('Lola Ridge', 73),
 ('Mark Akenside', 73),
 ('Freeman Edwin Miller', 72),
 ('Alfred Noyes', 71),
 ('Charles Stuart Calverley', 71),
 ('Gerard Manley Hopkins', 71),
 ('William Henry Davies', 71),
 ('Kate Seymour Maclean', 70),
 ('Thomas Oldham', 70),
 ('Anne Bronte', 69),
 ('Marietta Holley', 68),
 ('Susan Coolidge (Sarah Chauncey Woolsey)', 68),
 ('John Le Gay Brereton', 67),
 ('Horatio Alger, Jr.', 65),
 ('Adam Lindsay Gordon', 64),
 ('George W. Doneghy', 64),
 ('Helen Leah Reed', 64),
 ('Lydia Howard Sigourney', 64),
 ('Charles Hamilton Musgrove', 63),
 ('Edwin C. Ranck', 62),
 ('Arthur Macy', 61),
 ('Hilaire Belloc', 61),
 ('Margaret Steele Anderson', 61),
 ('Theodosia Garrison', 61),
 ('Alfred Joyce Kilmer (Joyce)', 60),
 ('Arthur Conan Doyle', 60),
 ('Virna Sheard', 60),
 ('William Henry Drummond', 60),
 ('James Barron Hope', 59),
 ('Alice Christiana Thompson Meynell', 58),
 ('Nathaniel Parker Willis', 58),
 ('Rose Hawthorne Lathrop', 57),
 ('Clark Ashton Smith', 55),
 ('Susanna Moodie', 55),
 ('H. P. Nichols', 54),
 ('Charles G. Leland', 53),
 ('Samuel Taylor Coleridge', 53),
 ('Arthur Thomas Quiller-Couch', 52),
 ('Dora Sigerson Shorter', 52),
 ('Emily Bronte', 52),
 ('James Joyce', 51),
 ('Sophie M. (Almon) Hensley', 51),
 ('Edward Shanks', 50),
 ('Washington Irving', 50),
 ('James Elroy Flecker', 49),
 ('Duncan Campbell Scott', 48),
 ('Fannie Isabelle Sherrick', 48),
 ('Ivan Sergeyevich Turgenev', 48),
 ('John Campbell', 48),
 ('Walter R. Cassels', 48),
 ('William Allingham', 48),
 ('Juliana Horatia Ewing', 47),
 ('Mary Ann H. T. Bigelow', 47),
 ('Frances Ellen Watkins Harper', 46),
 ('James Thomson -  (Bysshe Vanolis)', 46),
 ('Thomas William Hodgson Crosland', 46),
 ('Violet Jacob', 46),
 ('Fay Inchfawn', 44),
 ('Yehuda Amichai', 44),
 ('Eliza Paul Kirkbride Gurney', 43),
 ('Michael Earls', 43),
 ('Guy Wetmore Carryl', 41),
 ('George Augustus Baker, Jr.', 40),
 ('Kate Greenaway', 40),
 ('Oliver Goldsmith', 40),
 ('Anne Bradstreet', 39),
 ('John Wilmot', 39),
 ('Morris Rosenfeld', 39),
 ('Thomas Osborne Davis', 39),
 ('John Masefield', 38),
 ('Samuel Griswold Goodrich', 38),
 ('A. H. Laidlaw', 37),
 ('Giacomo Leopardi', 37),
 ('Nizar Qabbani', 37),
 ('Thomas Carew', 37),
 ('Aldous Leonard Huxley', 36),
 ('Barcroft Boake', 36),
 ('Edward Woodley Bowling', 36),
 ('R. C. Lehmann', 36),
 ('William Hayley', 36),
 ('Isabella Augusta, Lady Gregory', 35),
 ('Maurice Henry Hewlett', 35),
 ('Nancy Rebecca Campbell Glass', 35),
 ('Samuel Rogers', 34),
 ('Thomas Bailey Aldrich', 34),
 ('Thomas Campbell', 34),
 ('Edward Young', 33),
 ('Stephen Vincent Benet', 33),
 ('William Browne', 33),
 ('William F. Kirk', 33),
 ('Anna Akhmatova', 32),
 ('Bertolt Brecht', 32),
 ('Marriott Edgar', 32),
 ('Mary Gardiner Horsford', 32),
 ('A. R. Ammons', 31),
 ('John Kendall (Dum-Dum)', 31),
 ('Mary Hannay Foott', 30),
 ('Ringgold Wilmer Lardner', 30),
 ('James Williams', 29),
 ('Victoria Mary Sackville-West', 29),
 ('William Barnes', 29),
 ('Muriel Stuart', 27),
 ('Edward Smyth Jones', 26),
 ('George Wharton Edwards', 26),
 ('Helen Maria Williams', 26),
 ('Charlotte Bronte', 25),
 ('David Rorie M.D.', 25),
 ('James Henry Leigh Hunt', 25),
 ('Wilfred Edward Salter Owen', 25),
 ('Charles Churchill', 24),
 ('Frederic William Moorman', 24),
 ('Harriet Annie Wilkins', 24),
 ('John Drinkwater', 24),
 ('Richard Hunter', 24),
 ('Thomas Edward Brown', 24),
 ('Wilfrid Wilson Gibson', 24),
 ('Martin Farquhar Tupper', 23),
 ('Paul Bewsher', 23),
 ('William Vaughn Moody', 23),
 ('Edmund Spenser', 22),
 ('Thomas Runciman', 22),
 ('George W. Sands', 21),
 ('Owen Seaman', 21),
 ('Richard Harris Barham', 21),
 ('Will Carleton', 21),
 ('William Henry Giles Kingston', 21),
 ('Heinrich Hoffmann', 20),
 ('Jacob Bigelow', 20),
 ('Jan Kochanowski', 19),
 ('Joaquin Miller', 19),
 ('Joseph Addison', 19),
 ('Joseph Rodman Drake', 19),
 ('Lizzie Lawson', 19),
 ("Pat O'Cotter", 19),
 ("Thomas O'Hagan", 19),
 ('Toru Dutt', 19),
 ('Harold Edward Monro', 18),
 ('Katharine Lee Bates', 18),
 ('Horace Smith', 17),
 ('Leonard Leslie Brooke', 17),
 ('Ambrose Bierce', 16),
 ('Robert Lowell', 16),
 ('Adam Bernard Mickiewicz', 15),
 ('Alan L. Strang', 15),
 ('James Macpherson', 15),
 ('Lennox Amott', 15),
 ('Aphra Behn', 14),
 ('Aurelius Clemens Prudentius', 14),
 ('Robert Malise Bowyer Nichols', 14),
 ('George Wither', 13),
 ('Josephine Preston Peabody', 13),
 ('Lascelles Abercrombie', 13),
 ('Nicholas Breton', 13),
 ('Thomas Campion', 13),
 ('W.J. Turner', 13),
 ('Gordon Bottomley', 12),
 ('Michael Fairless', 12),
 ('Patrick Bronte', 12),
 ('Theodore Harding Rand', 12),
 ('Arthur Sherburne Hardy', 11),
 ('Elizabeth Jennings', 11),
 ('Francis Brett Young', 11),
 ('William Collins', 11),
 ('James Lister Cuthbertson', 10),
 ('James Thomson', 10),
 ('Ramakrishna, T.', 10),
 ('Ethel Allen Murphy', 9),
 ('John Gower', 9),
 ('Enid Derham', 8),
 ('Erasmus Darwin', 8),
 ('Frank James Prewett', 8),
 ('George Orwell (Eric Arthur Blair)', 8),
 ('Helen Beatrix Potter', 8),
 ('Stephen Phillips', 8),
 ('William Kerr', 8),
 ('John Milton Hayes', 7),
 ('Ada Langworthy Collier', 6),
 ('Andrejs Pumpurs', 6),
 ('Edmund Charles Blunden', 6),
 ('James Kenneth Stephen', 6),
 ('Margaret J. Preston', 6),
 ('Sam Walter Foss', 6),
 ('George Colman', 5),
 ('J. D. C. Fellow', 5),
 ('Manmohan Ghose', 5),
 ('Maria Gowen Brooks', 5),
 ('Ralph Hodgson', 5),
 ('Bert Leston Taylor', 4),
 ('Fredegond Shove', 4),
 ('Frederick Locker-Lampson', 4),
 ('James Hebblethwaite', 4),
 ('James Jeffrey Roche', 4),
 ('Peter Courtney Quennell, Sir', 4),
 ('Richard Arthur Warren Hughes', 4),
 ('Robert Laurence Binyon', 4),
 ('Samuel Lover', 4),
 ('Thomas William Heney', 4),
 ('Abijah M. Ide', 3),
 ('Arthur Shearly Cripps', 3),
 ('Francis Ledwidge', 3),
 ('George Canning', 3),
 ('Henry S. Leigh', 3),
 ('Samuel Butler', 3),
 ('Sir Francis Cowley Burnand', 3),
 ('Thomas Moult', 3),
 ('Wallace Irwin', 3),
 ('Washington Gladden', 3),
 ('William Makepeace Thackeray', 3),
 ('A. Hoatson', 2),
 ('Albert Bigelow Paine', 2),
 ('Arthur Guiterman', 2),
 ('Charles Henry Bennett', 2),
 ('Charles James Lever', 2),
 ('Clement Clarke Moore', 2),
 ('Clinton Scollard', 2),
 ('Edward James Mortimer Collins', 2),
 ('Edwin Arlington Robinson', 2),
 ('Elizabeth Anderson', 2),
 ('Eugene Fitch Ware', 2),
 ('Father Prout', 2),
 ('Frederic Edward Weatherly', 2),
 ('Harry Bache Smith', 2),
 ('Henry Cuyler Bunner', 2),
 ('Jennings Carmichael', 2),
 ('John Byrom', 2),
 ('John Godfrey Saxe I', 2),
 ('M. Forrest', 2),
 ('Martin Armstrong', 2),
 ('Richard Brinsley Butler Sheridan', 2),
 ('Robert William Chambers', 2),
 ('Samuel Minturn Peck', 2),
 ('Sir John Suckling', 2),
 ('Walter Parke', 2),
 ('William Edmondstoune Aytoun', 2),
 ('Abraham Cowley', 1),
 ('Alan Alexander Milne', 1),
 ('Alexander Rodger', 1),
 ('Alice Duer Miller', 1),
 ('Andrew Lang', 1),
 ('Anthony Charles Deane', 1),
 ('Arabella M Willson', 1),
 ('Arthur Grissom', 1),
 ('Bayard Taylor', 1),
 ('Bessie Morgan', 1),
 ('Captain C. Morris', 1),
 ('Casa Coraggio', 1),
 ('Charles Battell Loomis', 1),
 ('Charles Sibley', 1),
 ('David Law Proudfit', 1),
 ('Edmund Beale Sargant', 1),
 ('Edmund Hodgson Yates', 1),
 ('Edward Henry Palmer', 1),
 ('Edward Lysaght', 1),
 ('Evan Lloyd', 1),
 ('Florence E. Pratt', 1),
 ('Frances Miriam "Berry" Whitcher', 1),
 ('Francis Davison', 1),
 ('Francis Kenna', 1),
 ('Frank Gelett Burgess', 1),
 ('Frank Lebby Stanton', 1),
 ('Franklin Pierce Adams', 1),
 ('Fred W. Loring', 1),
 ('Frederick Langbridge', 1),
 ('Frederick Moxon', 1),
 ('George F. Warren', 1),
 ('George Francis Shults', 1),
 ('George Robert Sims', 1),
 ('H. C. Dodge', 1),
 ('H. E. Clarke', 1),
 ('H. H. C. C.', 1),
 ('H. H. Porter,', 1),
 ('H. P. Stevens', 1),
 ('Harlan Hoge Ballard', 1),
 ('Harry Romaine', 1),
 ('Henry Carey', 1),
 ('Herbert Asquith', 1),
 ('Hilda Johnson', 1),
 ('I. Rosenberg', 1),
 ('J. L. Duff', 1),
 ('J. P. Denison', 1),
 ('J. W. Foley', 1),
 ('James A. Sidey', 1),
 ('James Hogg', 1),
 ('James Robinson Planche', 1),
 ('James Russell Lowell', 1),
 ('James Tytler', 1),
 ('Jean C. Archer.', 1),
 ("John Boyle O'Reilly", 1),
 ('John Edward Hazzard', 1),
 ('John Kendrick Bangs', 1),
 ('John Marriott', 1),
 ('John Vance Cheney', 1),
 ('John William Ivimey', 1),
 ('Joseph Ashby-Sterry', 1),
 ('Joseph Burrows', 1),
 ('Lady T. Hastings', 1),
 ('Louis Shreve Osborne', 1),
 ('Louise Chandler Moulton', 1),
 ('Marcus Andrew Hislop Clarke', 1),
 ('Mark Lemon', 1),
 ('Mary Mapes Dodge', 1),
 ('Maurice Baring', 1),
 ('Nathan Haskell Dole', 1),
 ('Nixon Waterman', 1),
 ('Nora Perry', 1),
 ('Parmenas Mix', 1),
 ('Paul Thomas Gilbert', 1),
 ('Peter Anthony Motteux', 1),
 ('R. K. Munkittrick', 1),
 ('Reginald Heber', 1),
 ('Richard Lovelace', 1),
 ('Robert Calverley Trevelyan', 1),
 ('Ronald Ross', 1),
 ('Russell Hilliard Loines', 1),
 ('S. W. Gillinan', 1),
 ('Samuel Laman Blanchard', 1),
 ('Selleck Osborn', 1),
 ('Stephen Crane', 1),
 ('Sydney Jephcott', 1),
 ('Sydney Smith', 1),
 ('Thomas Haynes Bayly', 1),
 ('Thomas R. Ybarra', 1),
 ('Thomas Sturge Moore', 1),
 ('Tudor Storrs Jenks', 1),
 ('Virginia Carter Castleman', 1),
 ('W. J. Lampton', 1),
 ('William Allen Butler', 1),
 ('William Chatterton Dix', 1),
 ('William Congreve', 1),
 ('William Johnston', 1),
 ('William Maginn', 1),
 ('William Pitt Palmer', 1),
 ('William Sawyer', 1),
 ('William W. Fink', 1),
 ('Winthrop Mackworth Praed', 1)]

2. Let's check to see what time periods show up the most in this dataset to get a sense of its contours:

In [7]:
periods = poetry_df['period']
periods = periods.dropna()
time_periods = {}

for period in periods:
    if period in time_periods:
        time_periods[period] += 1
    else:
        time_periods[period] = 1

time_periods = sorted(time_periods.items(), key=lambda item: item[1], reverse=True)
time_periods

[('19th Century', 19025),
 ('20th Century', 4190),
 ('18th Century', 3132),
 ('16th-17th Centuries (Early Modern)', 2786),
 ('12th-15th Centuries (Middle English)', 484)]

## **Sample text dataset**

Though we wish we could analyze all the poems in this data, Colab tends to crash if we try to use more than 4-5,000 poems —  even with DistilBert, the smaller version of BERT. This is an important limitation to keep in mind. If you'd like to use more text data, you might consider upgrading to a paid version of Colab (with more memory or GPUs) or using a compute cluster.

To reduce the number of poems, we will take a random sample of 1,000 poems from four different time periods: the 20th Century, 19th Century, 18th Century, and the Early Modern period.

In [8]:
# Filter the DataFrame for only a given time period, then randomly sample 1000 rows
nineteenth_sample = poetry_df[poetry_df['period'] == '19th Century'].sample(1000)
twentieth_sample = poetry_df[poetry_df['period'] == '20th Century'].sample(1000)
eighteenth_sample = poetry_df[poetry_df['period'] == '18th Century'].sample(1000)
sixteenth_sample = poetry_df[poetry_df['period'] == '16th-17th Centuries (Early Modern)'].sample(1000)

In [9]:
# Merge these random samples into a new DataFrame
poetry_df = pd.concat([sixteenth_sample, eighteenth_sample, twentieth_sample, nineteenth_sample])

In [10]:
poetry_df['period'].value_counts()

period
16th-17th Centuries (Early Modern)    1000
18th Century                          1000
20th Century                          1000
19th Century                          1000
Name: count, dtype: int64

Finally, let's make a list of poems from our Pandas DataFrame.

In [11]:
poetry_texts = poetry_df['text'].tolist()

Let's examine a poem in our dataset:

In [12]:
len(poetry_texts)

4000

In [13]:
print(poetry_texts[0])

Nothing can be more loathsome than to see
Power conjoin'd with Nature's cruelty.

===================

## **Encode/tokenize text data for BERT**

Next we need to transform our poems into a format that BERT (via Huggingface) will understand. This is called *encoding* or *tokenizing* the data.

We will tokenize the poems with the `tokenizer()` from HuggingFace's `DistilBertTokenizerFast`. Here's what the `tokenizer()` will do:

1. Truncate the texts if they're more than 512 tokens or pad them if they're fewer than 512 tokens. If a word is not in BERT's vocabulary, it will be broken up into smaller "word pieces," demarcated by a `##`.

2. Add in special tokens to help BERT:
    - [CLS] — Start token of every document
    - [SEP] — Separator between each sentence
    - [PAD] — Padding at the end of the document as many times as necessary, up to 512 tokens
    - &#35;&#35; — Start of a "word piece"

Here we will load `DistilBertTokenizerFast` from HuggingFace library, which will help us transform and encode the texts so they can be used with BERT.

In [14]:
from transformers import DistilBertTokenizerFast

In [15]:
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

The `tokenizer()` will break word tokens into word pieces, truncate to 512 tokens, and add padding and special BERT tokens.

In [16]:
tokenized_poems = tokenizer(poetry_texts, truncation=True, padding=True, return_tensors="pt")

Let's examine the first tokenized poem. We can see that the special BERT tokens have been inserted where necessary.

In [17]:
' '.join(tokenized_poems[0].tokens)

"[CLS] nothing can be more lo ##ath ##some than to see power con ##jo ##in ' d with nature ' s cruelty . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]"

<br><br>

## **Load pre-trained BERT model**

Here we will load a pre-trained BERT model. To speed things up we will use a GPU, but using GPU involves a few extra steps.
The command `.to("cuda")` moves data from regular memory to the GPU's memory.

In [18]:
from transformers import DistilBertModel

In [19]:
model = DistilBertModel.from_pretrained('distilbert-base-uncased').to("cuda")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_transform.bias    | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## **Get BERT word embeddings for each document in a collection**

To get word embeddings for all the words in our collection, we will use a `for` loop.

For each poem in our list `poetry_texts`, we will tokenize the poem, and we will extract the vocabulary word ID for each word/token in the poem (to use for later reference). Then we will run the tokenized poem through the BERT model and extract the vectors for each word/token in the poem.

We thus create two big lists for all the poems in our collection — `doc_word_ids` and `doc_word_vectors`.

In [20]:
# List of vocabulary word IDs for all the words in each document (aka each poem)
doc_word_ids = []
# List of word vectors for all the words in each document (aka each poem)
doc_word_vectors = []

# Below we will slice our poem to ignore the first (0th) and last (-1) special BERT tokens
start_of_words = 1
end_of_words = -1

# Below we will index the 0th or first document, which will be the only document, since we're analzying one poem at a time
first_document = 0

for i, poem in enumerate(poetry_texts):

    # Here we tokenize each poem with the DistilBERT Tokenizer
    inputs = tokenizer(poem, return_tensors="pt", truncation=True, padding=True)

    # Here we extract the vocabulary word ids for all the words in the poem (the first or 0th document, since we only have one document)
    # We ignore the first and last special BERT tokens
    # We also convert from a Pytorch tensor to a numpy array
    doc_word_ids.append(inputs.input_ids[first_document].numpy()[start_of_words:end_of_words])

    # Here we send the tokenized poems to the GPU
    # The model is already on the GPU, but this poem isn't, so we send it to the GPU
    inputs.to("cuda")
    # Here we run the tokenized poem through the DistilBERT model
    outputs = model(**inputs)

    # We take every element from the first or 0th document, from the 2nd to the 2nd to last position
    # Grabbing the last layer is one way of getting token vectors. There are different ways to get vectors with different pros and cons
    doc_word_vectors.append(outputs.last_hidden_state[first_document,start_of_words:end_of_words,:].detach().cpu().numpy())

Confirm that we have the same number of documents for both the tokens and the vectors:

In [21]:
len(doc_word_ids), len(doc_word_vectors)

(4000, 4000)

In [22]:
doc_word_ids[0], doc_word_vectors[0]

(array([ 2498,  2064,  2022,  2062,  8840,  8988, 14045,  2084,  2000,
         2156,  2373,  9530,  5558,  2378,  1005,  1040,  2007,  3267,
         1005,  1055, 18186,  1012], dtype=int64),
 array([[-0.04058561, -0.01384196, -0.41690552, ...,  0.09674229,
          0.62953466,  0.06135523],
        [ 0.22985075,  0.3657562 , -0.2876274 , ..., -0.1577751 ,
          0.03393744,  0.34653556],
        [ 0.21734008,  0.04313137, -0.42023882, ..., -0.08093612,
         -0.05767591,  0.26987246],
        ...,
        [ 0.3843508 ,  0.09319965, -0.56893474, ..., -0.33802563,
          0.00715934,  0.37065113],
        [ 0.6680031 ,  0.27143028, -0.32429633, ..., -0.1073723 ,
         -0.04309234, -0.11918481],
        [ 0.790368  ,  0.07736056, -0.44672772, ..., -0.04817326,
         -0.44019973, -0.40373713]], dtype=float32))

## **Concatenate all word IDs/vectors for all documents**

Each element of these lists contains all the tokens/vectors for one document. But we want to concatenate them into two giant collections.

In [23]:
all_word_ids = np.concatenate(doc_word_ids)
all_word_vectors = np.concatenate(doc_word_vectors, axis=0)

We want to make comparisons between vectors quickly. One common option is *cosine similarity*, which measures the angle between vectors but ignores their length. We can speed this computation up by setting all the poem vectors to have length 1.0.

In [24]:
# Calculating the length of each vector (Pythagorean theorem)
row_norms = np.sqrt(np.sum(all_word_vectors ** 2, axis=1))
# Dividing every vector by its length
all_word_vectors /= row_norms[:,np.newaxis]

## **Find all word positions in a collection**

We can use the array `all_word_ids` to find all the places, or *positions*, in the collection where a word appears.

We can find a word's vocab ID in BERT with `tokenizer.vocab` and then check to see where/how many times this ID occurs in `all_word_ids`.

In [25]:
def get_word_positions(words):

  """This function accepts a list of words, rather than a single word"""

  # Get word/vocabulary ID from BERT for each word
  word_ids = [tokenizer.vocab[word] for word in words]

  # Find all the positions where the words occur in the collection
  word_positions = np.where(np.isin(all_word_ids, word_ids))[0]

  return word_positions

Here we'll check to see all the places where the word "bank" appears in the collection.

In [26]:
get_word_positions(["bank"])

array([ 30707,  62394,  71959,  75094,  93172,  93616, 173631, 184498,
       196492, 196629, 237880, 243507, 251480, 267254, 270552, 294294,
       326390, 332997, 347405, 347728, 373113, 382068, 414620, 423255,
       440662, 445271, 458543, 483896, 538514, 555857, 559517, 605622,
       636843, 685848, 783947, 814755, 836688, 843710, 855874, 856605,
       857665, 882869, 884999, 895041, 928699], dtype=int64)

In [27]:
word_positions = get_word_positions(["bank"])

## **Find word from word position**

Nice! Now we know all the positions where the word "bank" appears in the collection. But it would be more helpful to know the actual words that appear in context around it. To find these context words, we have to convert position IDs back into words.

In [28]:
# Here we create an array so that we can go backwards from numeric token IDs to words
word_lookup = np.empty(tokenizer.vocab_size, dtype="O")

for word, index in tokenizer.vocab.items():
    word_lookup[index] = word

Now we can use `word_lookup` to find a word based on its position in the collection.

In [29]:
word_positions = get_word_positions(["bank"])

for word_position in word_positions:
  print(word_position, word_lookup[all_word_ids[word_position]])

30707 bank
62394 bank
71959 bank
75094 bank
93172 bank
93616 bank
173631 bank
184498 bank
196492 bank
196629 bank
237880 bank
243507 bank
251480 bank
267254 bank
270552 bank
294294 bank
326390 bank
332997 bank
347405 bank
347728 bank
373113 bank
382068 bank
414620 bank
423255 bank
440662 bank
445271 bank
458543 bank
483896 bank
538514 bank
555857 bank
559517 bank
605622 bank
636843 bank
685848 bank
783947 bank
814755 bank
836688 bank
843710 bank
855874 bank
856605 bank
857665 bank
882869 bank
884999 bank
895041 bank
928699 bank

We can also look for the 3 words that come before "bank" and the 3 words that come after it.

In [30]:
word_positions = get_word_positions(["bank"])

for word_position in word_positions:

  # Slice 3 words before "bank"
  start_pos = word_position - 3
  # Slice 3 words after "bank"
  end_pos = word_position + 4

  context_words = word_lookup[all_word_ids[start_pos:end_pos]]
  # Join the words together
  context_words = ' '.join(context_words)
  print(word_position, context_words)

30707 then on the bank of jordan ,
62394 pride above thy bank ##es . "
71959 pri ##m ##rose bank did cross her
75094 a sunni ##e bank ##e outstretched lay
93172 ##tty * * bank , the which
93616 sober stream , bank ' d all
173631 , the blushing bank is all my
184498 lily by the bank , the pri
196492 on a summer bank , to sing
196629 bends on the bank , amid the
237880 ##s fra ##e bank to bra ##e
243507 the gravel ##ly bank thrown up by
251480 to the warm bank below , yellow
267254 , on some bank beside a river
270552 i . now bank an ' bra
294294 stood upon a bank , above her
326390 " see this bank - note -
332997 river ' s bank , in fable
347405 sunshine on the bank : no tear
347728 residence at allan bank . the long
373113 ##us on the bank , in vain
382068 ##no ' s bank , and on
414620 gently the green bank it la ##ves
423255 hedge , and bank , and stil
440662 george ' s bank when winds were
445271 a moss ##y bank ; where violet
458543 , though no bank would back '
483896 longing to regain bank - holidays ,
538514 ##rked under the bank of yo ##nder
555857 to the river bank and fee ##ble
559517 on the other bank crouch ##es april
605622 ##nation of a bank we couldn '
636843 . . the bank default ##er lee
685848 pri ##m ##rose bank shall there di
783947 the sweet sunny bank blue violet ##s
814755 , on a bank that lean '
836688 on that river bank where the waters
843710 roar aloud , bank - high for
855874 ##op from strawberry bank ; and he
856605 the moon ##lit bank , and thence
857665 a flower ##y bank i laid me
882869 upon a green bank , and her
884999 cave in the bank where the sly
895041 thee , by bank , sho ##al
928699 there beneath a bank of e ##gl

#### **In-class Question:**
In the above output, why we have many tokens like "##th", "##lving"?

**Answer:**

Our model is breaking the words down so that it can handle words more efficiently. ## is a special marker

Let's make some functions that will help us get the context words around a certain word position for whatever size window (certain number of words before and after) that we want.

The first function `get_context()` will simply return the tokens without cleaning them, and the second function `get_context_clean()` will return the tokens in a more readable fashion.

In [31]:
def get_context(word_id, window_size=10):

  """Simply get the tokens that occur before and after word position"""

  start_pos = max(0, word_id - window_size) # The token where we will start the context view
  end_pos = min(word_id + window_size + 1, len(all_word_ids)) # The token where we will end the context view

  # Make a list called tokens and use word_lookup to get the words for given token IDs from starting position up to the keyword
  tokens = [word_lookup[word] for word in all_word_ids[start_pos:end_pos] ]

  context_words = " ".join(tokens)

  return context_words

In [32]:
import re

def get_context_clean(word_id, window_size=10):

  """Get the tokens that occur before and after word position AND make them more readable"""

  keyword = word_lookup[all_word_ids[word_id]]
  start_pos = max(0, word_id - window_size) # The token where we will start the context view
  end_pos = min(word_id + window_size + 1, len(all_word_ids)) # The token where we will end the context view

  # Make a list called tokens and use word_lookup to get the words for given token IDs from starting position up to the keyword
  tokens = [word_lookup[word] for word in all_word_ids[start_pos:end_pos] ]

  # Make wordpieces slightly more readable
  # This is probably not the most efficient way to clean and correct for weird spacing
  context_words = " ".join(tokens)
  context_words = re.sub(r'\s+([##])', r'\1', context_words)
  context_words = re.sub(r'##', r'', context_words)
  context_words = re.sub('\s+\'s', '\'s', context_words)
  context_words = re.sub('\s+\'d', '\'d', context_words)
  context_words = re.sub('\s\'er', '\'er', context_words)
  context_words = re.sub(r'\s+([-,:?.!;])', r'\1', context_words)
  context_words = re.sub(r'([-\'"])\s+', r'\1', context_words)
  context_words = re.sub('\s+\'s', '\'s', context_words)
  context_words = re.sub('\s+\'d', '\'d', context_words)

  # Bold the keyword by putting asterisks around it
  if keyword in context_words:
    context_words = re.sub(f"\\b{keyword}\\b", f"**{keyword}**", context_words)
    context_words = re.sub(f"\\b({keyword}[esdtrlying]+)\\b", fr"**\1**", context_words)

  return context_words

<>:19: SyntaxWarning: invalid escape sequence '\s'
<>:20: SyntaxWarning: invalid escape sequence '\s'
<>:21: SyntaxWarning: invalid escape sequence '\s'
<>:24: SyntaxWarning: invalid escape sequence '\s'
<>:25: SyntaxWarning: invalid escape sequence '\s'
<>:19: SyntaxWarning: invalid escape sequence '\s'
<>:20: SyntaxWarning: invalid escape sequence '\s'
<>:21: SyntaxWarning: invalid escape sequence '\s'
<>:24: SyntaxWarning: invalid escape sequence '\s'
<>:25: SyntaxWarning: invalid escape sequence '\s'
C:\Users\leoxi\AppData\Local\Temp\ipykernel_29284\3190916756.py:19: SyntaxWarning: invalid escape sequence '\s'
  context_words = re.sub('\s+\'s', '\'s', context_words)
C:\Users\leoxi\AppData\Local\Temp\ipykernel_29284\3190916756.py:20: SyntaxWarning: invalid escape sequence '\s'
  context_words = re.sub('\s+\'d', '\'d', context_words)
C:\Users\leoxi\AppData\Local\Temp\ipykernel_29284\3190916756.py:21: SyntaxWarning: invalid escape sequence '\s'
  context_words = re.sub('\s\'er', '\'er', context_words)
C:\Users\leoxi\AppData\Local\Temp\ipykernel_29284\3190916756.py:24: SyntaxWarning: invalid escape sequence '\s'
  context_words = re.sub('\s+\'s', '\'s', context_words)
C:\Users\leoxi\AppData\Local\Temp\ipykernel_29284\3190916756.py:25: SyntaxWarning: invalid escape sequence '\s'
  context_words = re.sub('\s+\'d', '\'d', context_words)

To visualize the search keyword even more easily, we're going to import a couple of Python modules that will allow us to output text with bolded words and other styling. Here we will make a function `print_md()` that will allow us to print with Markdown styling.

In [33]:
from IPython.display import Markdown, display

def print_md(string):
    display(Markdown(string))

In [34]:
word_positions = get_word_positions(["bank"])

for word_position in word_positions:

  print_md(f"<br> {word_position}:  {get_context_clean(word_position)} <br>")

<br> 30707:  but return'd in vain. then on the **bank** of jordan, by a creek: where winds with <br>

<br> 62394:  up, rise, and swell with pride above thy **bankes**. "now is not every tide. tame <br>

<br> 71959:  , and running therewithal a primrose **bank** did cross her way, and gave my love a <br>

<br> 75094:  shore of muddie nile, upon a sunnie **banke** outstretched lay, in monstrous length, a might <br>

<br> 93172:  silver streaming themmes; whose rutty * * **bank**, the which his river hemmes, was pay <br>

<br> 93616:  to flow, like to a solemn sober stream, **bank**'d all with lilies, and the cream <br>

<br> 173631:  at th'shepherd's nose, the blushing **bank** is all my care, with hearth so red, <br>

<br> 184498:  t. iii. now blooms the lily by the **bank**, the primrose down the brae; <br>

<br> 196492:  green abode, and, seated on a summer **bank**, to sing no earthly music; in a spot <br>

<br> 196629:  ; from where the pensile birch bends on the **bank**, amid the clustered group of the dark hollie <br>

<br> 237880:  the burn comes down, and roars frae **bank** to brae; and bird and beast in covert <br>

<br> 243507:  washed by the sea, or on the gravelly **bank** thrown up by wintry torrents roaring loud, <br>

<br> 251480:  ample numbers stray. ii. then to the warm **bank** below, yellow with the morning-ray, and <br>

<br> 267254:  , and in our mossy valleys, on some **bank** beside a river clear, throw thy silk draperies <br>

<br> 270552:  one, kindly descends upon man! i. now **bank** an 'brae are claith'd in <br>

<br> 294294:  a pheasant, as she stood upon a **bank**, above her brood; with pride maternal beat her <br>

<br> 326390:  , a senator addressing, said: "see this **bank**-note-lo! a blessing-breathe on <br>

<br> 332997:  [ 1 ] thus, on the river's **bank**, in fabled lore, the rustic stands; <br>

<br> 347405:  the tree, the wood, the sunshine on the **bank**: no tear, no thought of time's <br>

<br> 347728:  grasmere, chiefly during our residence at allan **bank**. the long poem on my own education was, <br>

<br> 373113:  grow; and pale narcissus on the **bank**, in vain transformed, gazes on himself again. <br>

<br> 382068:  's golden store, on arno's **bank**, and on that bloomy shore, warbling <br>

<br> 414620:  purer stream courts him, as gently the green **bank** it laves, to blend th 'enfe <br>

<br> 423255:  waves efface pathway, and hedge, and **bank**, and stile!-i find but one <br>

<br> 440662:  she turned her home with cod from george's **bank** when winds were blowing. and i know from that <br>

<br> 445271:  where some sweet stream steals singing by a mossy **bank**; where violets vie in color with the summer <br>

<br> 458543:  , millionaires in legend-wealth, though no **bank** would back 'em, but old benny havens <br>

<br> 483896:  and bats, and mocked by hopeless longing to regain **bank**-holidays, and picture shows, and spats <br>

<br> 538514:  snare the bulky trout that lurked under the **bank** of yonder brook. indeed, he taught me <br>

<br> 555857:  ccasins. we crawled down to the river **bank** and feeble folk were we, that julie claire <br>

<br> 559517:  across a huge gulf... on the other **bank** crouches april with her hair as smooth and straight <br>

<br> 605622:  for the law; the stagnation of a **bank** we couldn 't stand; for our riot blood <br>

<br> 636843:  the watchman climbs the stair... the **bank** defaulter leers at a chaos of figures, <br>

<br> 685848:  hear all natures melodies. the primrose **bank** shall there dispense faint fragrance to the awake <br>

<br> 783947:  le around the ash tree, on the sweet sunny **bank** blue violets are seen, that tremble beneath the <br>

<br> 814755:  liquid south stole o 'er them, on a **bank** that lean'd to running water. there ' <br>

<br> 836688:  re and his crown, to brood on that river **bank** where the waters flashed and sank and burrowed in <br>

<br> 843710:  every cloud, the valley brooks they roar aloud, **bank**-high for the lowlands, lowlands, lowlands under <br>

<br> 855874:  low and crank, the little shallop from strawberry **bank**; and he rose in his stirrups and <br>

<br> 856605:  plain as the moral law just by the moonlit **bank**, and thence came a drunken man with no more <br>

<br> 857665:  wearied and oppressed, upon a flowery **bank** i laid me down to rest; beneath my feet <br>

<br> 882869:  e, she sat her downe upon a green **bank**, and her true love came riding bye. she <br>

<br> 884999:  s mounds are strown; cave in the **bank** where the sly stream steals; aloe that stab <br>

<br> 895041:  bird, while we follow, like thee, by **bank**, shoal, and quicksand, the <br>

<br> 928699:  eau, gay with loves, lie there beneath a **bank** of eglantine, that heaps a <br>

Here we make a list of all the context views for our keyword.

In [35]:
word_positions = get_word_positions(["bank"])

keyword_contexts = []
keyword_contexts_tokens = []

for position in word_positions:

  keyword_contexts.append(get_context_clean(position))
  keyword_contexts_tokens.append(get_context(position))

=========================

## **Get word vectors and reduce them with PCA**

Finally, we don't just want to *read* all the instances of "bank" in the collection, we want to *measure* the similarity of all the instances of "bank."

To measure similarity between all the instances of "bank," we will take the vectors for each instance and then use PCA to reduce each 768-dimensionsal vector to the 2 dimensions that capture the most variation.

In [36]:
from sklearn.decomposition import PCA

word_positions = get_word_positions(["bank"])

pca = PCA(n_components=2)

pca.fit(all_word_vectors[word_positions,:].T)

PCA(n_components=2)

Then, for convenience, we will put these PCA results into a Pandas DataFrame, which will use to generate an interactive plot.

In [37]:
df = pd.DataFrame({"x": pca.components_[0,:], "y": pca.components_[1,:],
                   "context": keyword_contexts, "tokens": keyword_contexts_tokens})
df.head()

,x,y,context,tokens
0,0.148578,0.242880,"but return'd in vain. then on the **bank** of jordan, by a creek: where winds with","but return ' d in vain . then on the bank of jordan , by a creek : where winds with"
1,0.139883,-0.066744,"up, rise, and swell with pride above thy **bankes**. ""now is not every tide. tame","up , rise , and swell with pride above thy bank ##es . "" now is not every tide . tame"
2,0.146224,-0.264926,", and running therewithal a primrose **bank** did cross her way, and gave my love a",", and running there ##with ##al a pri ##m ##rose bank did cross her way , and gave my love a"
3,0.142409,-0.088336,"shore of muddie nile, upon a sunnie **banke** outstretched lay, in monstrous length, a might","shore of mud ##die nile , upon a sunni ##e bank ##e outstretched lay , in monstrous length , a might"
4,0.150535,-0.053273,"silver streaming themmes; whose rutty * * **bank**, the which his river hemmes, was pay","silver streaming them ##mes ; whose ru ##tty * * bank , the which his river hem ##mes , was pay"

## **Match context with original text and metadata**

It's helpful (and fun!) to know where each instance of a word actually comes from — which poem, which poet, which time period, which Public-Domain-Poetry.com web page. The easiest method we've found for matching a bit of context with its original poem and metdata is to 1) add a tokenized version of each poem to our original Pandas Dataframe 2) check to see if the context shows up in a poem 3) and if so, grab the original poem and metadata.

In [38]:
# Tokenize all the poems
tokenized_poems = tokenizer(poetry_texts, truncation=True, padding=True, return_tensors="pt")

# Get a list of all the tokens for each poem
all_tokenized_poems = []
for i in range(len(tokenized_poems['input_ids'])):
  all_tokenized_poems.append(' '.join(tokenized_poems[i].tokens))

# Add them to the original DataFrame
poetry_df['tokens'] = all_tokenized_poems

In [39]:
poetry_df.head(2)

,author,title,text,lifespan,birth_year,death_year,link,period,tokens
20801,Robert Herrick,Cruelty Base In Commanders,Nothing can be more loathsome than to see\r\nPower conjoin'd with Nature's cruelty.,"Baptized - August 24, 1591- October 1674",1591.0,1674.0,http://public-domain-poetry.com/robert-herrick/cruelty-base-in-commanders-18958,16th-17th Centuries (Early Modern),[CLS] nothing can be more lo ##ath ##some than to see power con ##jo ##in ' d with nature ' s cruelty . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [P...
20608,Robert Herrick,Calling And Correcting,"God is not only merciful to call\r\nMen to repent, but when He strikes withal.","Baptized - August 24, 1591- October 1674",1591.0,1674.0,http://public-domain-poetry.com/robert-herrick/calling-and-correcting-19502,16th-17th Centuries (Early Modern),"[CLS] god is not only mer ##ciful to call men to rep ##ent , but when he strikes with ##al . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [..."

In [40]:
def find_original_poem(rows):

  """This function checks to see whether the context tokens show up in the original poem,
  and if so, returns metadata about the title, author, period, and URL for that poem"""

  text = rows['tokens'].replace('**', '')
  text = text[55:70]

  if poetry_df['tokens'].str.contains(text, regex=False).any() == True :
    row = poetry_df[poetry_df['tokens'].str.contains(text, regex=False)].values[0]
    title, author, period, link = row[0], row[1], row[7], row[6]
    return author, title, period, link
  else:
    return None, None, None, None

In [41]:
df[['title', 'author', 'period', 'link']] = df.apply(find_original_poem, axis='columns', result_type='expand')

In [42]:
df

,x,y,context,tokens,title,author,period,link
0,0.148578,0.242880,"but return'd in vain. then on the **bank** of jordan, by a creek: where winds with","but return ' d in vain . then on the bank of jordan , by a creek : where winds with",Paradise Regained - The Second Book,John Milton,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/john-milton/paradise-regained-the-second-book-8323
1,0.139883,-0.066744,"up, rise, and swell with pride above thy **bankes**. ""now is not every tide. tame","up , rise , and swell with pride above thy bank ##es . "" now is not every tide . tame",The Speeches Of Gratulations,Ben Jonson,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/ben-jonson/speeches-of-gratulations-2539
2,0.146224,-0.264926,", and running therewithal a primrose **bank** did cross her way, and gave my love a",", and running there ##with ##al a pri ##m ##rose bank did cross her way , and gave my love a",A Song Upon Silvia,Robert Herrick,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/robert-herrick/song-upon-silvia-19163
3,0.142409,-0.088336,"shore of muddie nile, upon a sunnie **banke** outstretched lay, in monstrous length, a might","shore of mud ##die nile , upon a sunni ##e bank ##e outstretched lay , in monstrous length , a might",Visions Of The Worlds Vanitie,Edmund Spenser,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/edmund-spenser/visions-of-the-worlds-vanitie-32234
4,0.150535,-0.053273,"silver streaming themmes; whose rutty * * **bank**, the which his river hemmes, was pay","silver streaming them ##mes ; whose ru ##tty * * bank , the which his river hem ##mes , was pay","Prothalamion: Or, A Spousall Verse",Edmund Spenser,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/edmund-spenser/prothalamion-or-a-spousall-verse-32239
5,0.132393,-0.186152,"to flow, like to a solemn sober stream, **bank**'d all with lilies, and the cream","to flow , like to a solemn sober stream , bank ' d all with lil ##ies , and the cream",The Wassail,Robert Herrick,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/robert-herrick/wassail-2307
6,0.147089,-0.205165,"at th'shepherd's nose, the blushing **bank** is all my care, with hearth so red,","at th ' shepherd ' s nose , the blushing bank is all my care , with hearth so red ,",Blind Man's Buff,William Blake,18th Century,http://public-domain-poetry.com/william-blake/blind-mans-buff-9293
7,0.158698,-0.002662,"t. iii. now blooms the lily by the **bank**, the primrose down the brae;","##t . iii . now blooms the lily by the bank , the pri ##m ##rose down the bra ##e ;","Lament Of Mary, Queen Of Scots, On The Approach Of Spring",Robert Burns,18th Century,http://public-domain-poetry.com/robert-burns/lament-of-mary-queen-of-scots-on-the-approach-of-spring-10010
8,0.151986,0.067832,"green abode, and, seated on a summer **bank**, to sing no earthly music; in a spot","green ab ##ode , and , seated on a summer bank , to sing no earthly music ; in a spot","Cadland,[1] Southampton River",William Lisle Bowles,18th Century,http://public-domain-poetry.com/william-lisle-bowles/cadland-southampton-river-9408
9,0.153606,0.165385,"; from where the pensile birch bends on the **bank**, amid the clustered group of the dark hollie","; from where the pens ##ile birch bends on the bank , amid the clustered group of the dark ho ##llie","Cadland,[1] Southampton River",William Lisle Bowles,18th Century,http://public-domain-poetry.com/william-lisle-bowles/cadland-southampton-river-9408
10,0.150806,-0.115120,"the burn comes down, and roars frae **bank** to brae; and bird and beast in covert","the burn comes down , and roar ##s fra ##e bank to bra ##e ; and bird and beast in covert",Winter. A Dirge,Robert Burns,18th Century,http://public-domain-poetry.com/robert-burns/winter-a-dirge-9890
11,0.156575,0.084061,"washed by the sea, or on the gravelly **bank** thrown up by wintry torrents roaring loud,","washed by the sea , or on the gravel ##ly bank thrown up by win ##try torre ##nts roaring loud ,",The Task. Book I. The Sofa,William Cowper,18th Century,http://public-domain-poetry.com/william-cowper/task-book-i-the-sofa-12992
12,0.153447,0.180753,"ample numbers stray. ii. then to the warm **bank** below, yellow with the morning-ray, and","ample numbers stray . ii . then to the warm bank below , yellow with the morning - ray , and","Odes From Horace. - [1]On The Pleasures Of Rural Life. Book The Fifth, Epode The Second",Anna Seward,18th Century,http://public-domain-poetry.com/anna-seward/odes-from-horace-1on-the-pleasures-of-rural-life-book-the-fifth-epode-the-second-31214
13,0.152659,0.200540,", and in our mossy valleys, on some **bank** beside a river clear, throw thy silk draperies",", and in our moss ##y valleys , on some bank beside a river clear , throw thy silk draper ##ies",To Summer,William Blake,18th Century,http://public-domain-poetry.com/william-blake/to-summer-9283
14,0.146987,-0.168075,"one, kindly descends upon man! i. now **bank** an 'brae are claith'd in","one , kindly descends upon man ! i . now bank an ' bra ##e are cl ##aith ' d in",Cassillis' Banks,Robert Burns,18th Century,http://public-domain-poetry.com/robert-burns/cassillis-banks-10290
15,0.156132,0.074570,"a pheasant, as she stood upon a **bank**, above her brood; with pride maternal beat her","a ph ##ea ##sant , as she stood upon a bank , above her brood ; with pride maternal beat her",Philosopher And Pheasant,John Gay,18th Century,http://public-domain-poetry.com/john-gay/philosopher-and-pheasant-34767
16,0.145058,-0.245505,", a senator addressing, said: ""see this **bank**-note-lo! a blessing-breathe on",", a senator addressing , said : "" see this bank - note - lo ! a blessing - breathe on",Juggler And Vice,John Gay,18th Century,http://public-domain-poetry.com/john-gay/juggler-and-vice-34794
17,0.146492,0.270074,"[ 1 ] thus, on the river's **bank**, in fabled lore, the rustic stands;","[ 1 ] thus , on the river ' s bank , in fable ##d lore , the rustic stands ;","Sonnet LXIX. To A Young Lady, Purposing To Marry A Man Of Immoral Character In The Hope Of His Reformation",Anna Seward,18th Century,http://public-domain-poetry.com/anna-seward/sonnet-lxix-to-a-young-lady-purposing-to-marry-a-man-of-immoral-character-in-the-hope-of-his-reform-31159
18,0.155335,0.097950,"the tree, the wood, the sunshine on the **bank**: no tear, no thought of time's","the tree , the wood , the sunshine on the bank : no tear , no thought of time ' s",On A Beautiful Landscape,William Lisle Bowles,18th Century,http://public-domain-poetry.com/william-lisle-bowles/on-a-beautiful-landscape-9332
19,0.125491,-0.054217,"grasmere, chiefly during our residence at allan **bank**. the long poem on my own education was,","gr ##as ##mere , chiefly during our residence at allan bank . the long poem on my own education was ,",The Excursion. Note & Preface,William Wordsworth,18th Century,http://public-domain-poetry.com/william-wordsworth/excursion-note-preface-4208
20,0.156263,0.154469,"grow; and pale narcissus on the **bank**, in vain transformed, gazes on himself again.","grow ; and pale na ##rc ##iss ##us on the bank , in vain transformed , gazes on himself again .",In Imitation Of Cowley : The Garden,Alexander Pope,18th Century,http://public-domain-poetry.com/alexander-pope/in-imitation-of-cowley-the-garden-1639
21,0.156064,-0.015031,"'s golden store, on arno's **bank**, and on that bloomy shore, warbling","' s golden store , on ar ##no ' s bank , and on that bloom ##y shore , war ##bling",Sonnet LXXV. Subject Continued,Anna Seward,18th Century,http://public-domain-poetry.com/anna-seward/sonnet-lxxv-subject-continued-31165
22,0.151522,0.023017,"purer stream courts him, as gently the green **bank** it laves, to blend th 'enfe","pure ##r stream courts him , as gently the green bank it la ##ves , to blend th ' en ##fe","Odes From Horace. - To M'cenas. Book The First, Ode The First",Anna Seward,18th Century,http://public-domain-poetry.com/anna-seward/odes-from-horace-to-mcenas-book-the-first-ode-the-first-31191
23,0.151880,-0.094430,"waves efface pathway, and hedge, and **bank**, and stile!-i find but one","waves e ##ffa ##ce pathway , and hedge , and bank , and stil ##e ! - i find but one",Sonnet LXXXVIII. The Prospect A Flooded Vale,Anna Seward,18th Century,http://public-domain-poetry.com/anna-seward/sonnet-lxxxviii-the-prospect-a-flooded-vale-31178
24,0.142835,-0.037099,she turned her home with cod from george's **bank** when winds were blowing. and i know from that,she turned her home with cod from george ' s bank when winds were blowing . and i know from that,The Flower Boat,Robert Lee Frost,20th Century,http://public-domain-poetry.com/robert-lee-frost/flower-boat-1162
25,0.155898,0.070937,where some sweet stream steals singing by a mossy **bank**; where violets vie in color with the summer,where some sweet stream steals singing by a moss ##y bank ; where violet ##s vie in color with the summer,In Summer Time,Paul Laurence Dunbar,20th Century,http://public-domain-poetry.com/paul-laurence-dunbar/in-summer-time-15134
26,0.135974,-0.269954,", millionaires in legend-wealth, though no **bank** would back 'em, but old benny havens",", millionaire ##s in legend - wealth , though no bank would back ' em , but old benny haven ##s",Old Hudson Rovers,Michael Earls,20th Century,http://public-domain-poetry.com/michael-earls/old-hudson-rovers-15199
27,0.135968,-0.227377,"and bats, and mocked by hopeless longing to regain **bank**-holidays, and picture shows, and spats","and bats , and mocked by hopeless longing to regain bank - holidays , and picture shows , and spat ##s",Dreamers,Siegfried Loraine Sassoon,20th Century,http://public-domain-poetry.com/siegfried-loraine-sassoon/dreamers-30398
28,0.151223,0.146522,"snare the bulky trout that lurked under the **bank** of yonder brook. indeed, he taught me","s ##nare the bulky trout that lu ##rked under the bank of yo ##nder brook . indeed , he taught me",Michael Oaktree,Alfred Noyes,20th Century,http://public-domain-poetry.com/alfred-noyes/michael-oaktree-28075
29,0.145515,0.212500,"ccasins. we crawled down to the river **bank** and feeble folk were we, that julie claire","##cca ##sin ##s . we crawled down to the river bank and fee ##ble folk were we , that julie claire",Barb-Wire Bill,Robert William Service,20th Century,http://public-domain-poetry.com/robert-william-service/barb-wire-bill-30949
30,0.146241,0.184435,across a huge gulf... on the other **bank** crouches april with her hair as smooth and straight,across a huge gulf . . . on the other bank crouch ##es april with her hair as smooth and straight,Winter Dream,Aldous Leonard Huxley,20th Century,http://public-domain-poetry.com/aldous-leonard-huxley/winter-dream-21082
31,0.141329,-0.245038,for the law; the stagnation of a **bank** we couldn 't stand; for our riot blood,for the law ; the st ##ag ##nation of a bank we couldn ' t stand ; for our riot blood,The Rhyme Of The Restless Ones,Robert William Service,20th Century,http://public-domain-poetry.com/robert-william-service/rhyme-of-the-restless-ones-31010
32,0.139709,-0.257044,"the watchman climbs the stair... the **bank** defaulter leers at a chaos of figures,","the watch ##man climbs the stair . . . the bank default ##er lee ##rs at a chaos of figures ,",The House Of Dust: Part 03: 01: As Evening Falls,Conrad Potter Aiken,20th Century,http://public-domain-poetry.com/conrad-potter-aiken/house-of-dust-part-03-01-as-evening-falls-7240
33,0.153486,-0.129915,hear all natures melodies. the primrose **bank** shall there dispense faint fragrance to the awake,hear all nature ##s melodies . the pri ##m ##rose bank shall there di ##sp ##ense faint fragrance to the awake,Ode,Robert Southey,19th Century,http://public-domain-poetry.com/robert-southey/ode-32095
34,0.151017,0.045969,"le around the ash tree, on the sweet sunny **bank** blue violets are seen, that tremble beneath the","##le around the ash tree , on the sweet sunny bank blue violet ##s are seen , that tremble beneath the",May,Nathaniel Parker Willis,19th Century,http://public-domain-poetry.com/nathaniel-parker-willis/may-34668
35,0.159339,0.050713,"liquid south stole o 'er them, on a **bank** that lean'd to running water. there '","liquid south stole o ' er them , on a bank that lean ' d to running water . there '",April,Nathaniel Parker Willis,19th Century,http://public-domain-poetry.com/nathaniel-parker-willis/april-34652
36,0.146203,0.174761,"re and his crown, to brood on that river **bank** where the waters flashed and sank and burrowed in","##re and his crown , to brood on that river bank where the waters flashed and sank and burr ##owed in",Song Of The Fifth River,Rudyard Kipling,19th Century,http://public-domain-poetry.com/rudyard-kipling/song-of-the-fifth-river-3473
37,0.149702,-0.077450,"every cloud, the valley brooks they roar aloud, **bank**-high for the lowlands, lowlands, lowlands under","every cloud , the valley brooks they roar aloud , bank - high for the lowlands , lowlands , lowlands under",The Floods,Rudyard Kipling,19th Century,http://public-domain-poetry.com/rudyard-kipling/floods-3225
38,0.151379,-0.002502,"low and crank, the little shallop from strawberry **bank**; and he rose in his stirrups and","low and crank , the little shall ##op from strawberry bank ; and he rose in his stir ##rup ##s and",John Underhill,John Greenleaf Whittier,19th Century,http://public-domain-poetry.com/john-greenleaf-whittier/john-underhill-5947
39,0.148897,-0.031574,"plain as the moral law just by the moonlit **bank**, and thence came a drunken man with no more","plain as the moral law just by the moon ##lit bank , and thence came a drunken man with no more",The Ghost that Jim Saw,Bret Harte (Francis),19th Century,http://public-domain-poetry.com/francis-bret-harte/ghost-that-jim-saw-8775
40,0.156678,0.001902,"wearied and oppressed, upon a flowery **bank** i laid me down to rest; beneath my feet","wear ##ied and op ##pressed , upon a flower ##y bank i laid me down to rest ; beneath my feet",The Happy Cottagers,Patrick Bronte,19th Century,http://public-domain-poetry.com/patrick-bronte/happy-cottagers-9626
41,0.154137,0.062905,"e, she sat her downe upon a green **bank**, and her true love came riding bye. she","##e , she sat her down ##e upon a green bank , and her true love came riding bye . she",The Bailiff's Daughter of Islington,George Wharton Edwards,19th Century,http://public-domain-poetry.com/george-wharton-edwards/bailiffs-daughter-of-islington-15222
42,0.155911,0.096714,s mounds are strown; cave in the **bank** where the sly stream steals; aloe that stab,s mounds are st ##row ##n ; cave in the bank where the sly stream steals ; al ##oe that stab,Cupid's Arrows,Rudyard Kipling,19th Century,http://public-domain-poetry.com/rudyard-kipling/cupids-arrows-3571
43,0.153071,-0.025309,"bird, while we follow, like thee, by **bank**, shoal, and quicksand, the","bird , while we follow , like thee , by bank , sho ##al , and quick ##san ##d , the",The Phantom Fleet,Alfred Noyes,20th Century,http://public-domain-poetry.com/alfred-noyes/phantom-fleet-28074
44,0.149823,0.099621,"eau, gay with loves, lie there beneath a **bank** of eglantine, that heaps a","##eau , gay with loves , lie there beneath a bank of e ##gl ##ant ##ine , that heap ##s a",The Bleeding Hand; Or The Sprig Of Eglantine Given To A Maid,Robert Herrick,16th-17th Centuries (Early Modern),http://public-domain-poetry.com/robert-herrick/bleeding-hand-or-the-sprig-of-eglantine-given-to-a-maid-2292

============================

## **Plot word embeddings**

Lastly, we will plot the words vectors from this DataFrame with the Python data viz library [Altair](https://altair-viz.github.io/gallery/scatter_tooltips.html).

In [43]:
import altair as alt

In [44]:
alt.Chart(df,title="Word Similarity: Bank").mark_circle(size=200).encode(
    alt.X('x',
        scale=alt.Scale(zero=False)
    ), y="y",
    # If you click a point, take you to the URL link
    href="link",
    # The categories that show up in the hover tooltip
    tooltip=['title', 'context', 'author', 'period']
    ).interactive().properties(
    width=500,
    height=500
)

c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

## **Plot word embeddings from keywords (all at once!)**

We can put the code from the previous few sections into a single cell and plot the BERT word embeddings for any list of words. Let's look at the words "nature," "religion," "science," and "art."

In [45]:
# List of keywords that you want to compare
keywords = ['nature', 'religion', 'science', 'art']

# How to color the points in the plot. The other option is "period" for time period
color_by = 'word'

# Get all word positions
word_positions = get_word_positions(keywords)

# Get all contexts around the words
keyword_contexts = []
keyword_contexts_tokens = []
words = []

for position in word_positions:
  words.append(word_lookup[all_word_ids[position]])
  keyword_contexts.append(get_context_clean(position))
  keyword_contexts_tokens.append(get_context(position))

# Reduce word vectors with PCA
pca = PCA(n_components=2)
pca.fit(all_word_vectors[word_positions,:].T)

# Make a DataFrame with PCA results
df = pd.DataFrame({"x": pca.components_[0,:], "y": pca.components_[1,:],
                   "context": keyword_contexts, "tokens": keyword_contexts_tokens, "word": words})
# Match original text and metadata
df[['title', 'author', 'period', 'link']] = df.apply(find_original_poem, axis='columns', result_type='expand')

# Rename columns so that the context shows up as the "title" in the tooltip (bigger and bolded)
df = df.rename(columns={'title': 'poem_title', 'context': 'title'})

# Make the plot
alt.Chart(df, title=f"Word Similarity: {', '.join(keywords).title()}").mark_circle(size=200).encode(
    alt.X('x',
        scale=alt.Scale(zero=False)
    ), y="y",
    color= color_by,
    href="link",
    tooltip=['title', 'word', 'poem_title', 'author', 'period']
    ).interactive().properties(
    width=500,
    height=500
)

c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

#### **In-class Question:**
Given the above visulization of keywords in different poems, what can you infer? E.g., How similar are the words "nature" and "art" in a collection of 16th-20th century English language poems?

**Answer:** Art and nature sit on differrent y values, but the sit on the similar X values, meaning that the poem represents them in a similar way, but the way they are percieved is affected

#### **In-class Practice:**

Let's examine the words "nature," "religion," "science," and "art" again but this time color the points by their time period.

In [46]:
# List of keywords that you want to compare
keywords = ['nature', 'religion', 'science', 'art']

# How to color the points in the plot. The other option is "period" for time period
color_by = 'period'

# Get all word positions
word_positions = get_word_positions(keywords)

# Get all contexts around the words
keyword_contexts = []
keyword_contexts_tokens = []
words = []

for position in word_positions:
  words.append(word_lookup[all_word_ids[position]])
  keyword_contexts.append(get_context_clean(position))
  keyword_contexts_tokens.append(get_context(position))

# Reduce word vectors with PCA
pca = PCA(n_components=2)
pca.fit(all_word_vectors[word_positions,:].T)

# Make a DataFrame with PCA results
df = pd.DataFrame({"x": pca.components_[0,:], "y": pca.components_[1,:],
                   "context": keyword_contexts, "tokens": keyword_contexts_tokens, "word": words})
# Match original text and metadata
df[['title', 'author', 'period', 'link']] = df.apply(find_original_poem, axis='columns', result_type='expand')

# Rename columns so that the context shows up as the "title" in the tooltip (bigger and bolded)
df = df.rename(columns={'title': 'poem_title', 'context': 'title'})

# Make the plot
alt.Chart(df, title=f"Word Similarity: {', '.join(keywords).title()}").mark_circle(size=200).encode(
    alt.X('x',
        scale=alt.Scale(zero=False)
    ), y="y",
    color= color_by,
    href="link",
    tooltip=['title', 'word', 'poem_title', 'author', 'period']
    ).interactive().properties(
    width=500,
    height=500
)

c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

#### **In-class Question:**
Given the above visulization of keywords in different periods, what can you infer? E.g., Do 20th-century poets use the word "science" differently than 16th-century poets?

**Answer:**

#### **In-class Practice:**

Let's compare the words 'head', 'heart', 'eye', 'arm', and 'leg.'

What can you infer from the results?

In [47]:
# List of keywords that you want to compare
keywords = ['head', 'heart', 'eye', 'arm', 'leg']

Try some other words, like "ring"

In [54]:
# List of keywords that you want to compare
keywords = ['ring']

# How to color the points in the plot. The other option is "period" for time period
color_by = 'word'

# Get all word positions
word_positions = get_word_positions(keywords)

# Get all contexts around the words
keyword_contexts = []
keyword_contexts_tokens = []
words = []

for position in word_positions:
  words.append(word_lookup[all_word_ids[position]])
  keyword_contexts.append(get_context_clean(position))
  keyword_contexts_tokens.append(get_context(position))

# Reduce word vectors with PCA
pca = PCA(n_components=2)
pca.fit(all_word_vectors[word_positions,:].T)

# Make a DataFrame with PCA results
df = pd.DataFrame({"x": pca.components_[0,:], "y": pca.components_[1,:],
                   "context": keyword_contexts, "tokens": keyword_contexts_tokens, "word": words})
# Match original text and metadata
df[['title', 'author', 'period', 'link']] = df.apply(find_original_poem, axis='columns', result_type='expand')

# Rename columns so that the context shows up as the "title" in the tooltip (bigger and bolded)
df = df.rename(columns={'title': 'poem_title', 'context': 'title'})

# Make the plot
alt.Chart(df, title=f"Word Similarity: {', '.join(keywords).title()}").mark_circle(size=200).encode(
    alt.X('x',
        scale=alt.Scale(zero=False)
    ), y="y",
    color= color_by,
    href="link",
    tooltip=['title', 'word', 'poem_title', 'author', 'period']
    ).interactive().properties(
    width=500,
    height=500
)

c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
c:\Users\leoxi\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

Write to CSV

In [49]:
df.to_csv('bert-word-ring.csv', index=False, encoding='utf-8')

==============================

## **Find word similarity from a specific word position**

We can also search *all* of the vectors for words similar to a query word.

In [50]:
def get_nearest(query_vector, n=100):
  cosines = all_word_vectors.dot(query_vector)
  ordering = np.flip(np.argsort(cosines))
  return ordering[:n]

To do so, we need to find the specific word position of our desired search keyword.

In [51]:
word_positions = get_word_positions(['bank'])

for word_position in word_positions:

  print_md(f"<br> {word_position}: {get_context_clean(word_position)} <br>")

<br> 30707: but return'd in vain. then on the **bank** of jordan, by a creek: where winds with <br>

<br> 62394: up, rise, and swell with pride above thy **bankes**. "now is not every tide. tame <br>

<br> 71959: , and running therewithal a primrose **bank** did cross her way, and gave my love a <br>

<br> 75094: shore of muddie nile, upon a sunnie **banke** outstretched lay, in monstrous length, a might <br>

<br> 93172: silver streaming themmes; whose rutty * * **bank**, the which his river hemmes, was pay <br>

<br> 93616: to flow, like to a solemn sober stream, **bank**'d all with lilies, and the cream <br>

<br> 173631: at th'shepherd's nose, the blushing **bank** is all my care, with hearth so red, <br>

<br> 184498: t. iii. now blooms the lily by the **bank**, the primrose down the brae; <br>

<br> 196492: green abode, and, seated on a summer **bank**, to sing no earthly music; in a spot <br>

<br> 196629: ; from where the pensile birch bends on the **bank**, amid the clustered group of the dark hollie <br>

<br> 237880: the burn comes down, and roars frae **bank** to brae; and bird and beast in covert <br>

<br> 243507: washed by the sea, or on the gravelly **bank** thrown up by wintry torrents roaring loud, <br>

<br> 251480: ample numbers stray. ii. then to the warm **bank** below, yellow with the morning-ray, and <br>

<br> 267254: , and in our mossy valleys, on some **bank** beside a river clear, throw thy silk draperies <br>

<br> 270552: one, kindly descends upon man! i. now **bank** an 'brae are claith'd in <br>

<br> 294294: a pheasant, as she stood upon a **bank**, above her brood; with pride maternal beat her <br>

<br> 326390: , a senator addressing, said: "see this **bank**-note-lo! a blessing-breathe on <br>

<br> 332997: [ 1 ] thus, on the river's **bank**, in fabled lore, the rustic stands; <br>

<br> 347405: the tree, the wood, the sunshine on the **bank**: no tear, no thought of time's <br>

<br> 347728: grasmere, chiefly during our residence at allan **bank**. the long poem on my own education was, <br>

<br> 373113: grow; and pale narcissus on the **bank**, in vain transformed, gazes on himself again. <br>

<br> 382068: 's golden store, on arno's **bank**, and on that bloomy shore, warbling <br>

<br> 414620: purer stream courts him, as gently the green **bank** it laves, to blend th 'enfe <br>

<br> 423255: waves efface pathway, and hedge, and **bank**, and stile!-i find but one <br>

<br> 440662: she turned her home with cod from george's **bank** when winds were blowing. and i know from that <br>

<br> 445271: where some sweet stream steals singing by a mossy **bank**; where violets vie in color with the summer <br>

<br> 458543: , millionaires in legend-wealth, though no **bank** would back 'em, but old benny havens <br>

<br> 483896: and bats, and mocked by hopeless longing to regain **bank**-holidays, and picture shows, and spats <br>

<br> 538514: snare the bulky trout that lurked under the **bank** of yonder brook. indeed, he taught me <br>

<br> 555857: ccasins. we crawled down to the river **bank** and feeble folk were we, that julie claire <br>

<br> 559517: across a huge gulf... on the other **bank** crouches april with her hair as smooth and straight <br>

<br> 605622: for the law; the stagnation of a **bank** we couldn 't stand; for our riot blood <br>

<br> 636843: the watchman climbs the stair... the **bank** defaulter leers at a chaos of figures, <br>

<br> 685848: hear all natures melodies. the primrose **bank** shall there dispense faint fragrance to the awake <br>

<br> 783947: le around the ash tree, on the sweet sunny **bank** blue violets are seen, that tremble beneath the <br>

<br> 814755: liquid south stole o 'er them, on a **bank** that lean'd to running water. there ' <br>

<br> 836688: re and his crown, to brood on that river **bank** where the waters flashed and sank and burrowed in <br>

<br> 843710: every cloud, the valley brooks they roar aloud, **bank**-high for the lowlands, lowlands, lowlands under <br>

<br> 855874: low and crank, the little shallop from strawberry **bank**; and he rose in his stirrups and <br>

<br> 856605: plain as the moral law just by the moonlit **bank**, and thence came a drunken man with no more <br>

<br> 857665: wearied and oppressed, upon a flowery **bank** i laid me down to rest; beneath my feet <br>

<br> 882869: e, she sat her downe upon a green **bank**, and her true love came riding bye. she <br>

<br> 884999: s mounds are strown; cave in the **bank** where the sly stream steals; aloe that stab <br>

<br> 895041: bird, while we follow, like thee, by **bank**, shoal, and quicksand, the <br>

<br> 928699: eau, gay with loves, lie there beneath a **bank** of eglantine, that heaps a <br>

> 186552: , and in our mossy valleys, on some bank beside a river clear, throw thy silk draperies

In [52]:
keyword_position = 186552

In [53]:
contexts = [get_context_clean(token_id) for token_id in get_nearest(all_word_vectors[keyword_position,:])]

for context in contexts:
  print_md(context)

ert her genial sway, and taught the peaceful **world** her power to obey; content, a female of

as his inferior flame the new-enlightened **world** no more should need; he saw a greater sun

rl'd upon th 'affrighted **world**; sword, fire and famine with fell fury met

like a boy's. we have given the **world** our passion we have naught for death but toys

, and hurled upon th 'affrighted **world**? sword, fire, and famine, with fell

devout, a veil of ecstasy! while yet the **world** was young, and men were few, nor lurking

each other to the quick in modes which the gross **world** no sense hath to perceive, no soul to

a tall palace, shapen so all the wondering **world** might know the joy he had of his moorish

love even with my life decay; lest the wise **world** should look into your moan, and mock you with

justice from above, which tam'd the savage **world** to your divine commands? majesty of the nature of

, we beat about with br dear, had the **world** in its caprice deigned to proclaim '

tossed, lit by a living love the wilted **world** knew nothing of: scared momently by gaingiving

the surly sullen bell give warning to the **world** that i am fled from this vile **world** with vile

the third we resign: thus scorning the **world**, and superior to fate, i drive on my

and play, careless of what the censuring **world** may say; bright cloe! object of my

the fiery course of the sun that warms the **world** with the sense and the splendour of

borrow, ornament; still was its inner **world** a place reached by the dews of heavenly grace

ye in the age gone by, who ruled the **world** a **world** how lovely then! and guided still the

must have vent if but in silent tears. the **world** may deem from outward looks that heart is hard

him: he laughed, and rode away. the **world** with sunshine was aflood, and glad were maid

fixed immoveably the frame of the round **world**, and built, by laws as strong, a

: no sigh, no murmer the wide **world** shall hear; from every face he wipes off

, who, standing on some bluff, regards the **world** with soul as tough,-the sun, the

and what the nation owes, fly the forgetful **world**, and in thy arms repose. 13 the

his startled ear 'abstain from sin! the **world** around solicits his desire, and kindles

flowing from his heart, that all the wandering **world** would gain. the honorable ardleigh wyse

importance find, blind to themselves, as the hard **world** is blind! wit they esteem a gay but worthless

of thee; now this ill-wresting **world** is grown so bad, mad slanderers by

to do or see of things that in the great **world** be, daisy! again i talk to thee,

! o, love! what is it in this **world** of ours which makes it fatal to be loved?

e; whence thou dost pour upon the **world** a flood of harmony, with instinct more divine;

moonbeams that were lost on summer nights the **world** forgets may here be prisoned by the frost

partners hath your call fetched from the shadowy **world**. 'tis said, that warnings ye disp

thy pack, and lighten thy back. the **world** was a fool, ere since it begun,

rand by the wings they wore. what a fair **world** were ours for verse to paint, if power could

weep'st, fair cloe, see the **world** in sympathy with thee. the chearful birds

father, in this lordly space, the great **world** turns with worship in its face. for that glad

enslave the free-born soul, that **world** whose vaunted skill in selfish interest pervert

that shut-in sea a glorious symbol to the **world** of all that's great and free; and

all his haughty views can find in this **world** yields to death? the fair, the brave,

i gazed long since, on the cold, clouded **world**, and cried, beautiful vision, loved, adored

thing in the **world** to do! oh! the **world** looks glad, for the spring has smiled, and

augment. great julius, whom now all the **world** admires the more he grew in years, the

all was changed. from a transfigured **world** the moon's ghost fled, the smoke of

the things that make ye so much honored of the **world** as ye bee are such as ( without my simple

quiet length of hill, the sleeping grief of the **world**?-out of it we had like imaginations

more, than all the vanquish'd **world** could yield before. till barbarous nations,

music of mankind to birth, and make the whole **world** one. "vii. and those old comrades rise

tears are the showers that fertilize this **world**; and memory of things precious keepeth warm the

which noiseless, 'mid the changes of the **world**, holds its inevitable course, the tide of years

ntation when the wind sighs; how will fare the **world** whose wonder was the very proof of me? memory

oh! precarious state of this vain transient **world**! all powerful time, what dost thou not

the heart's breaking seas. i leave the **world** to-morrow, what news for fairyland?

sound. "heroic deeds in every age command the **world**'s esteem; each finds a place in history

in the eyes of all posterity that wear this **world** out to the ending doom. so, till the

the gift to take, and smite this sleeping **world** awake. the old gate clicks, and down the

sorrow where fairy rotas play, i leave the **world** to-morrow for ever and a day. men

it in storied line, so that the **world** may remember black samson of brandywine. to margot

. boldly he sprang to the strife of the **world**, as a deer to the mountain-top careless

! how god does love this poor and sinful **world**! the stars behold him as he passes on,

the rough, remote, dull paths of this dull **world**, no yes, 'twas a cause,

, their doom! iii upon those servants of another **world** when madding power her bolts had hurled, their

not wish the burning blaze of fame around a restless **world**, the thunder and the storm of praise in crowded

all the **world** can boast, to all the **world** illustriously are lost! o let my muse her

come! behold behold! for this! our living **world** the old pompeii sees; and built

'd upon thy works by the detracting **world** what malice can suggest; let the rout say

eve i sat me down and wept, because the **world** to me seemed nowise good; still autumn was

his celestial face, and from the forlorn **world** his visage hide, stealing unseen to west with

lucretius take his void, and all the **world** is quite destroy'd. deny descart

the massachusetts bay. the **world** might bless and the **world** might ban, what did it matter the perfect man

all men, saints and sons of shame, the **world** will never see his kingdom bright. stars of all

men must go; you set the image of the **world** high for your heart's idolatry,

no sense can understand, to understand that all the **world** may know, such wit, such sense, eyes

? laugh and be merry, remember, better the **world** with a song, better the **world** with a blow

gods, with an intellect clear, that mirrors the **world** as it glides; he has seen all that

conquest for her subjects 'ease, and bids the **world** attend her terms of peace. thee, gracious

hearse, when all the breathers of this **world** are dead; you still shall live, such virtue

thee, ever thou 'lt live on! the **world** delights whate 'er is bright to stain

s distress, but a long glad astonishment at the **world**'s beauty and your own. the pity of

lt thou stay; whilst we, who make the **world** our home, to softer climes impatient roam

this, sweet as the gods in song. the **world**, in my account, no sight affords more

the thing he saw. arabian fiction never filled the **world** with half the wonders that were wrought for him.

holiday ') 'be warned! i feel the **world** grow old, and off olympus fades the gold of

fur good ain 't flowin 'round this **world** fur every fool to sup; you 've

umber,--with sweet pain of richest **world**'s desire,--prevail,

.... nepenthe of this struggling **world**, thou who dost stay mad care when her

then, "she murmurs; this is what the **world** calls bliss, oh! for objects less unworthy

; and would at the same time justify to the **world** my choice of the great name prefixed to it

, native pride, make yourselves rules to all the **world** beside; reason, collected in herself, disdains

commanding her with delegated powers to beautify the **world**, and bless the night? why does each animated

'll give o 'er, and bid the **world** good-night. 'tis but a flying minute

image, man! go forth into the nether **world**; "for dust thou art, and unto dust

's glory, lived a while to lend the **world** your scent and smile. but when your own fair

s ears. and lest, at last, the **world** should learn heart-secrets; lest that sweet wolf

a louder trumpet, and more dreadful fields; the **world** alarm'd, both earth and heaven o '

on each other'shadow forth thee: 'the **world** hath not another ( tho 'all her fair

'd voice proclaim! so shall the listening **world** be told [ 6 ] medus, and cold

to work my will, and at my deeds the **world** shall thrill. my words shall rouse the slumb

through summer air, her lucid fingers hushed the **world** to sleep. o as i stand this latest moon

shoreless hush of region light, through a new **world**, undreamed of, undesired,